import {parseBu} from './bu-parser.js';
const $=id=>document.getElementById(id),nf=new Intl.NumberFormat('pt-BR'),pf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2,minimumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map',{scrollWheelZoom:false}).setView([-15,-49],4);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);
let polygons=L.layerGroup().addTo(map),points=L.layerGroup().addTo(map),outline=L.layerGroup().addTo(map),city=null,records=new Map(),groups=[],boundary=null,municipal=null,run=0,failed=0,lookup=[],busy=false;
const colors={13:'#ca4661',22:'#218b79',other:'#c09131',pending:'#aab0b8'};
const sum=rows=>{const votes={};for(const r of rows)for(const v of r.votes)votes[v.number]=(votes[v.number]||0)+v.votes;return votes;};
const candidates=()=>municipal?.carg?.find(c=>c.cd==='1')?.agr?.flatMap(a=>a.par.flatMap(p=>p.cand))||[];
function result(g){const keys=[...new Set(g.sites.flatMap(s=>s.sections.map(sec=>s.id.split('-')[0]+'-'+sec)))];const rows=keys.map(k=>records.get(k)).filter(Boolean),votes=sum(rows);const valid=candidates().filter(c=>c.dvt==='Válido').map(c=>c.n);const validVotes=Object.fromEntries(Object.entries(votes).filter(([n])=>valid.includes(n)));const ranking=Object.entries(validVotes).sort((a,b)=>b[1]-a[1]);const total=ranking.reduce((s,x)=>s+x[1],0),complete=rows.length===keys.length&&valid.length>0;const winner=complete&&total?(ranking.length>1&&ranking[0][1]===ranking[1][1]?'other':ranking[0][0]):'pending';return{keys,rows,votes:validVotes,total,complete,winner,color:colors[winner]||colors.other};}
function popup(g){const r=result(g),others=r.total-(r.votes['13']||0)-(r.votes['22']||0);const row=(name,v)=>`<div class="vote"><span>${name}</span><strong>${nf.format(v)} · ${r.total?pf.format(v/r.total*100):'—'}%</strong></div>`;return `<div class="popup-title">${g.sites.map(s=>esc(s.name)).join('<br>')}</div><div class="popup-address">${g.sites.map(s=>esc(s.address)+' · '+esc(s.neighborhood)).join('<br>')}</div>${row('Lula',r.votes['13']||0)}${row('Flávio Bolsonaro',r.votes['22']||0)}${row('Demais candidatos',others)}<div class="popup-coverage">${r.complete?'Todos os boletins deste ponto foram lidos.':'PARCIAL: percentuais apenas dos boletins disponíveis.'}<br>Boletins: ${r.rows.length}/${r.keys.length}. Votos válidos: ${nf.format(r.total)}.<br>Brancos: ${nf.format(r.rows.reduce((s,x)=>s+x.blank,0))}; nulos: ${nf.format(r.rows.reduce((s,x)=>s+x.nullVotes,0))}.</div><details class="source-link"><summary>Boletins oficiais de origem</summary>${r.rows.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">Zona ${x.zone}, seção ${x.section}</a><br>`).join('')}</details>`;}
function paint(){for(const g of groups){const r=result(g);g.polygon?.setStyle({fillColor:r.color,fillOpacity:r.complete?.57:.2});g.marker?.setStyle({color:r.color,fillColor:r.color});g.polygon?.bindPopup(()=>popup(g));g.marker?.bindPopup(()=>popup(g));}updateStatus();}
function expected(){return [...new Set(city.sites.flatMap(s=>s.sections.map(sec=>s.id.split('-')[0]+'-'+sec)))];}
function updateStatus(){if(!city)return;const total=expected().length,got=records.size,completed=groups.filter(g=>result(g).complete).length;const mapped=groups.reduce((n,g)=>n+g.sites.length,0);$('heading').textContent=`${city.name} (${city.uf.toUpperCase()})`;$('bar').max=total;$('bar').value=got;$('progress').textContent=`${nf.format(got)} de ${nf.format(total)} boletins lidos (${pf.format(got/total*100)}%). ${completed}/${groups.length} pontos com dados completos. ${mapped}/${city.sites.length} locais com coordenadas utilizáveis.${busy?' Consultando o TSE…':''}${failed?' '+failed+' consultas não puderam ser concluídas.':''}`;
 const summed=sum([...records.values()]),cs=candidates(),divergent=cs.filter(c=>(summed[c.n]||0)!==Number(c.vap));const fully=got===total&&cs.length>0&&!divergent.length;
 const stamp=[...records.values()].map(x=>x.checked).sort().at(-1);const checked=stamp?new Date(stamp).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})+' Brasília':'—';
 const generation=municipal?`${municipal.dg} ${municipal.hg} (horário do TSE)`:'não disponível';
 $('validation').textContent=fully?`✓ Somas dos boletins conferidas com o TSE para todos os ${cs.length} candidatos. Resultado municipal gerado em ${generation}. Consulta: ${checked}.`:`${got===total&&cs.length?'As somas dos boletins divergem do resultado municipal; não classificar como resultado final. ':'Aguardando cobertura completa e conferência das somas. '}Resultado municipal: ${generation}. Consulta: ${checked}.`;
 $('refresh').disabled=busy;$('download').disabled=!got;
}
function geometry(){const valid=city.sites.filter(s=>s.lat!==null&&s.lon!==null&&turf.booleanPointInPolygon([s.lon,s.lat],boundary));const grouped=new Map();for(const s of valid){const key=s.lon.toFixed(6)+','+s.lat.toFixed(6);if(!grouped.has(key))grouped.set(key,{lon:s.lon,lat:s.lat,sites:[]});grouped.get(key).sites.push(s);}groups=[...grouped.values()];if(!groups.length)throw Error('Nenhum local com coordenada válida dentro do município.');const box=turf.bbox(boundary),factor=Math.cos((box[1]+box[3])/2*Math.PI/180),coords=groups.map(g=>[g.lon*factor,g.lat]);const voronoi=d3.Delaunay.from(coords).voronoi([box[0]*factor,box[1],box[2]*factor,box[3]]);
 groups.forEach((g,i)=>{const cell=voronoi.cellPolygon(i);if(cell){try{const raw=turf.polygon([cell.map(([x,y])=>[x/factor,y])]);const clipped=turf.intersect(raw,boundary);if(clipped){g.polygon=L.geoJSON(clipped,{style:{color:'#fff',weight:1,fillColor:colors.pending,fillOpacity:.2}}).addTo(polygons);g.polygon.bindTooltip(g.sites[0].name);}}catch(e){console.warn('Recorte indisponível',g.sites[0].name);}}
 g.marker=L.circleMarker([g.lat,g.lon],{radius:4,color:colors.pending,weight:1,fillOpacity:1}).addTo(points);g.marker.bindTooltip(g.sites[0].name);});
 L.geoJSON(boundary,{style:{color:'#576773',weight:1.3,fillOpacity:0,interactive:false}}).addTo(outline);map.fitBounds(L.latLngBounds(groups.map(g=>[g.lat,g.lon])).pad(.14),{padding:[20,20],maxZoom:14});paint();}
let nextRequest=0;async function controlledFetch(url,options){const slot=Math.max(Date.now(),nextRequest);nextRequest=slot+30;await new Promise(r=>setTimeout(r,Math.max(0,slot-Date.now())));return fetch(url,options);}
async function json(url){const r=await controlledFetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json();}
async function loadMunicipal(c){const u=`https://resultados.tse.jus.br/oficial/ele2026/6257/dados/${c.uf}/${c.uf}${c.code}-c0001-e006257-u.json`;const j=await json(u);if(j.f!=='o'||j.ele!=='6257'||j.t!=='1'||j.cdabr!==c.code||!j.carg?.some(x=>x.cd==='1'))throw Error('Resultado municipal não corresponde à eleição selecionada');return j;}
async function fetchRecords(c,token){busy=true;failed=0;updateStatus();let pos=0;const keys=expected();let notFound=0,stop=false;async function worker(){while(pos<keys.length&&token===run&&!stop){const key=keys[pos++];const [zone,section]=key.split('-'),root=`https://resultados.tse.jus.br/oficial/ele2026/arquivo-urna/3220/dados/${c.uf}/${c.code}/${zone}/${section}`,auxUrl=`${root}/p003220-${c.uf}-m${c.code}-z${zone}-s${section}-aux.json`;try{const a=await json(auxUrl);if(a.f?.toLowerCase()!=='o')throw Error('Não oficial');const active=a.hashes.filter(h=>['recebido','totalizado'].includes(h.st.toLowerCase()));if(active.length!==1)throw Error('Boletim sem hash único ativo');const h=active[0],file=h.arq.find(x=>x.tp==='bu')?.nm;if(!/^[a-zA-Z0-9]+$/.test(h.hash)||!file||!new RegExp(`^o03220${c.uf}\\d{13}-bu\\.dat$`).test(file))throw Error('Arquivo BU inesperado');const url=`${root}/${h.hash}/${file}`,r=await controlledFetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('BU HTTP '+r.status);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>1000000)throw Error('BU excede limite');const b=parseBu(bytes,c.code,zone,section);if(token!==run)return;records.set(key,{...b,url,auxUrl,checked:new Date().toISOString()});}catch(e){if(token===run){failed++;records.delete(key);if(String(e).includes('404')&&++notFound>=4)stop=true;}}if(token===run&&pos%10===0)paint();await new Promise(r=>setTimeout(r,150));}}
 await Promise.all(Array.from({length:8},worker));if(token!==run)return;busy=false;paint();}
async function select(code){const token=++run;busy=true;city=null;records=new Map();groups=[];polygons.clearLayers();points.clearLayers();outline.clearLayers();$('heading').textContent='Carregando município…';$('bar').value=0;$('refresh').disabled=true;$('download').disabled=true;$('progress').textContent='Carregando locais e limite municipal…';$('validation').textContent='';try{const c=await json(`cidades/${code}.json`);const url=`https://servicodados.ibge.gov.br/api/v3/malhas/municipios/${c.ibge}?formato=application/vnd.geo+json&qualidade=minima`;const [b,m]=await Promise.all([json(url),loadMunicipal(c)]);if(token!==run)return;city=c;municipal=m;boundary=b.features?b.features[0]:b;$('boundarySource').href=url;$('city').value=`${c.name} (${c.uf.toUpperCase()})`;history.replaceState(null,'',`?municipio=${code}`);geometry();
 if(code==='61492'){const seed=await json('semente.json');if(token!==run)return;for(const r of seed.records)records.set(r.zone+'-'+r.section,r);paint();}await fetchRecords(c,token);
 }catch(e){if(token!==run)return;busy=false;$('progress').textContent='Não foi possível completar a consulta: '+e.message+'. Tente novamente.';$('refresh').disabled=false;}}
$('search').addEventListener('submit',e=>{e.preventDefault();const text=$('city').value.trim().toUpperCase();const c=lookup.find(c=>`${c.name} (${c.uf.toUpperCase()})`===text)||lookup.find(c=>c.code===text||c.ibge===text);if(c)select(c.code);else $('progress').textContent='Escolha uma cidade da lista, incluindo a UF.';});
$('refresh').addEventListener('click',()=>city&&select(city.code));
$('download').addEventListener('click',()=>{if(!city)return;const rows=[['municipio','uf','local','endereco','latitude','longitude','boletins_lidos','boletins_esperados','lula_votos','flavio_votos','demais_votos','validos','lula_pct','flavio_pct','status','captura_utc']];for(const s of city.sites){const r=result({sites:[s]});rows.push([city.name,city.uf.toUpperCase(),s.name,s.address,s.lat,s.lon,r.rows.length,r.keys.length,r.votes['13']||0,r.votes['22']||0,r.total-(r.votes['13']||0)-(r.votes['22']||0),r.total,r.total?(r.votes['13']||0)/r.total*100:'',r.total?(r.votes['22']||0)/r.total*100:'',r.complete?'BOLETINS_COMPLETOS':'PARCIAL',new Date().toISOString()]);}const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`votos-locais-${city.code}-2026.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);});
try{lookup=await json('cidades.json');$('cities').innerHTML=lookup.map(c=>`<option value="${esc(c.name)} (${c.uf.toUpperCase()})"></option>`).join('');const code=new URLSearchParams(location.search).get('municipio')||'61492';await select(lookup.some(c=>c.code===code)?code:'61492');}catch(e){$('progress').textContent='Cadastro indisponível: '+e.message;}
