import {parseBu} from './bu-parser.js';
const $=id=>document.getElementById(id),nf=new Intl.NumberFormat('pt-BR'),pf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2,minimumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map',{scrollWheelZoom:false}).setView([-15,-49],4);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);
let polygons=L.layerGroup().addTo(map),points=L.layerGroup().addTo(map),outline=L.layerGroup().addTo(map),city=null,records=new Map(),groups=[],boundary=null,municipal=null,run=0,failed=0,lookup=[],busy=false,queue=null,errors=new Map(),openGroup=null;
const storage=new Promise(resolve=>{const r=indexedDB.open('votos-vizinhanca-2026',1);r.onupgradeneeded=()=>r.result.createObjectStore('cidades',{keyPath:'code'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);});
async function cached(code){try{const db=await storage;if(!db)return null;return await new Promise(resolve=>{const r=db.transaction('cidades').objectStore('cidades').get(code);r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);});}catch{return null;}}
async function saveCache(c,rs){try{const db=await storage;if(!db||!rs.size)return;db.transaction('cidades','readwrite').objectStore('cidades').put({code:c.code,records:[...rs.values()],saved:new Date().toISOString()});}catch{}}
let requestedLocal=new URLSearchParams(location.search).get('local');
let addressMarker=null,addressLine=null;const addressMemory=new Map();
const colors={13:'#ca4661',22:'#218b79',other:'#c09131',pending:'#aab0b8'};
const sum=rows=>{const votes={};for(const r of rows)for(const v of r.votes)votes[v.number]=(votes[v.number]||0)+v.votes;return votes;};
const candidates=()=>municipal?.carg?.find(c=>c.cd==='1')?.agr?.flatMap(a=>a.par.flatMap(p=>p.cand))||[];
function result(g){const keys=[...new Set(g.sites.flatMap(s=>s.sections.map(sec=>s.id.split('-')[0]+'-'+sec)))];const rows=keys.map(k=>records.get(k)).filter(Boolean),votes=sum(rows);const valid=candidates().filter(c=>c.dvt==='Válido').map(c=>c.n);const validVotes=Object.fromEntries(Object.entries(votes).filter(([n])=>valid.includes(n)));const ranking=Object.entries(validVotes).sort((a,b)=>b[1]-a[1]);const total=ranking.reduce((s,x)=>s+x[1],0),complete=rows.length===keys.length&&valid.length>0&&rows.every(x=>!x.stale);const winner=complete&&total?(ranking.length>1&&ranking[0][1]===ranking[1][1]?'other':ranking[0][0]):'pending';return{keys,rows,votes:validVotes,total,complete,winner,color:colors[winner]||colors.other};}
function popup(g){
 const r=result(g),empty=!r.rows.length,issue=r.keys.map(k=>errors.get(k)).filter(Boolean),others=r.total-(r.votes['13']||0)-(r.votes['22']||0);
 const row=(name,v)=>`<div class="vote"><span>${name}</span><strong>${nf.format(v)} · ${r.total?pf.format(v/r.total*100):'—'}%</strong></div>`;
 const notice=issue.length?'A consulta ao TSE falhou: '+esc([...new Set(issue)].join('; '))+'. Isso não significa zero votos.':'Consultando os boletins deste local. Os números aparecerão aqui assim que forem lidos.';
 const waiting='<p class="loading-votes"><strong>Votação ainda não carregada</strong><br>'+notice+'</p>';
 const votes=empty?waiting:row('Lula',r.votes['13']||0)+row('Flávio Bolsonaro',r.votes['22']||0)+row('Demais candidatos',others);
 const label=r.complete?'Todos os boletins deste ponto foram lidos.':empty?'Aguardando consulta ao TSE.':'PARCIAL ou captura anterior: percentuais apenas dos boletins exibidos.';
 const totals=empty?'Os votos ainda não estão disponíveis nesta consulta.':`Votos válidos: ${nf.format(r.total)}.<br>Brancos: ${nf.format(r.rows.reduce((s,x)=>s+x.blank,0))}; nulos: ${nf.format(r.rows.reduce((s,x)=>s+x.nullVotes,0))}.`;
 return `<div class="popup-title">${g.sites.map(s=>esc(s.name)).join('<br>')}</div><div class="popup-address">${g.sites.map(s=>esc(s.address)+' · '+esc(s.neighborhood)).join('<br>')}</div>${votes}<div class="popup-coverage">${label}<br>Boletins: ${r.rows.length}/${r.keys.length}. ${totals}</div><details class="source-link"><summary>Boletins oficiais de origem</summary>${r.rows.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">Zona ${x.zone}, seção ${x.section}</a><br>`).join('')}</details>`;
}
function paint(){for(const g of groups){const r=result(g);g.polygon?.setStyle({fillColor:r.color,fillOpacity:r.complete?.57:.2});g.marker?.setStyle({color:r.color,fillColor:r.color});}if(openGroup&&map._popup?.isOpen())map._popup.setContent(popup(openGroup));updateStatus();}
function expected(){return [...new Set(city.sites.flatMap(s=>s.sections.map(sec=>s.id.split('-')[0]+'-'+sec)))];}
function updateStatus(){if(!city)return;const total=expected().length,got=records.size,completed=groups.filter(g=>result(g).complete).length;const mapped=groups.reduce((n,g)=>n+g.sites.length,0);$('heading').textContent=`${city.name} (${city.uf.toUpperCase()})`;$('bar').max=total;$('bar').value=got;$('progress').textContent=`${nf.format(got)} de ${nf.format(total)} boletins lidos (${pf.format(got/total*100)}%). ${completed}/${groups.length} pontos com dados completos. ${mapped}/${city.sites.length} locais com coordenadas utilizáveis.${busy?' Consultando o TSE…':' Clique numa área ou busque o local para carregar seus votos.'}${failed?' '+failed+' consultas não puderam ser concluídas. Motivo: '+[...new Set(errors.values())].slice(0,2).join('; '):''}`;
 const summed=sum([...records.values()]),cs=candidates(),divergent=cs.filter(c=>(summed[c.n]||0)!==Number(c.vap));const fully=got===total&&cs.length>0&&!divergent.length&&[...records.values()].every(r=>!r.stale);
 const stamp=[...records.values()].map(x=>x.checked).sort().at(-1);const checked=stamp?new Date(stamp).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})+' Brasília':'—';
 const generation=municipal?`${municipal.dg} ${municipal.hg} (horário do TSE)`:'não disponível';
 $('validation').textContent=fully?`✓ Somas dos boletins conferidas com o TSE para todos os ${cs.length} candidatos. Resultado municipal gerado em ${generation}. Consulta: ${checked}.`:`${got===total&&cs.length?'As somas dos boletins divergem do resultado municipal; não classificar como resultado final. ':'Aguardando cobertura completa e conferência das somas. '}Resultado municipal: ${generation}. Consulta: ${checked}.`;
 $('refresh').disabled=busy;$('download').disabled=!got;
}
function prioritize(g){if(!queue||!busy)return;const preferred=result(g).keys.filter(k=>!records.has(k)||records.get(k).stale);const waiting=new Set(queue.items.slice(queue.pos));const first=preferred.filter(k=>waiting.has(k));const tail=queue.items.slice(queue.pos).filter(k=>!first.includes(k));queue.items.splice(queue.pos,queue.items.length-queue.pos,...first,...tail);}
function open(g){history.replaceState(null,'',`?municipio=${city.code}&local=${encodeURIComponent(g.sites[0].id)}`);map.closePopup();openGroup=g;prioritize(g);L.popup().setLatLng([g.lat,g.lon]).setContent(popup(g)).openOn(map);if(!busy){const missing=result(g).keys.filter(k=>!records.has(k)&&!errors.has(k));if(missing.length)fetchRecords(city,run,missing);}}
map.on('popupclose',()=>{openGroup=null;});
function setupLocalSearch(){ $('nearby').hidden=false;$('place').value='';$('places').innerHTML=city.sites.map(s=>`<option value="${esc(s.name)} — ${esc(s.neighborhood)}"></option>`).join('');}
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
$('localSearch').addEventListener('submit',e=>{e.preventDefault();const q=normalize($('place').value.trim());if(!q||!city)return;let matched=groups.filter(g=>g.sites.some(s=>normalize(s.name+' — '+s.neighborhood).includes(q)||normalize(s.neighborhood+' '+s.address+' '+s.name).includes(q)));if(!matched.length){$('localHint').textContent='Nenhum local encontrado. Busque pelo bairro, escola ou endereço cadastrado do local de votação.';return;}$('localHint').textContent=`${matched.length} ponto(s) encontrado(s). Clique em outro resultado abaixo para abrir.`;$('matches').innerHTML='';for(const g of matched.slice(0,30)){const button=document.createElement('button');button.type='button';button.textContent=g.sites[0].name+' · '+g.sites[0].neighborhood;button.addEventListener('click',()=>{map.setView([g.lat,g.lon],16);open(g);});$('matches').append(button);}map.fitBounds(L.latLngBounds(matched.map(g=>[g.lat,g.lon])).pad(.15),{maxZoom:16});open(matched[0]);});
function geometry(){const valid=city.sites.filter(s=>s.lat!==null&&s.lon!==null&&turf.booleanPointInPolygon([s.lon,s.lat],boundary));const grouped=new Map();for(const s of valid){const key=s.lon.toFixed(6)+','+s.lat.toFixed(6);if(!grouped.has(key))grouped.set(key,{lon:s.lon,lat:s.lat,sites:[]});grouped.get(key).sites.push(s);}groups=[...grouped.values()];if(!groups.length)throw Error('Nenhum local com coordenada válida dentro do município.');const box=turf.bbox(boundary),factor=Math.cos((box[1]+box[3])/2*Math.PI/180),coords=groups.map(g=>[g.lon*factor,g.lat]);const voronoi=d3.Delaunay.from(coords).voronoi([box[0]*factor,box[1],box[2]*factor,box[3]]);
 groups.forEach((g,i)=>{const cell=voronoi.cellPolygon(i);if(cell){try{const raw=turf.polygon([cell.map(([x,y])=>[x/factor,y])]);const clipped=turf.intersect(raw,boundary);if(clipped){g.polygon=L.geoJSON(clipped,{style:{color:'#fff',weight:1,fillColor:colors.pending,fillOpacity:.2}}).addTo(polygons);g.polygon.bindTooltip(g.sites[0].name);g.polygon.on('click',()=>open(g));}}catch(e){console.warn('Recorte indisponível',g.sites[0].name);}}
 g.marker=L.circleMarker([g.lat,g.lon],{radius:4,color:colors.pending,weight:1,fillOpacity:1}).addTo(points);g.marker.bindTooltip(g.sites[0].name);g.marker.on('click',()=>open(g));});
 L.geoJSON(boundary,{style:{color:'#576773',weight:1.3,fillOpacity:0,interactive:false}}).addTo(outline);map.fitBounds(L.latLngBounds(groups.map(g=>[g.lat,g.lon])).pad(.14),{padding:[20,20],maxZoom:14});paint();}
let nextRequest=0;async function controlledFetch(url,options){const slot=Math.max(Date.now(),nextRequest);nextRequest=slot+30;await new Promise(r=>setTimeout(r,Math.max(0,slot-Date.now())));return fetch(url,options);}
async function json(url){const r=await controlledFetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json();}
async function loadMunicipal(c){const u=`https://resultados.tse.jus.br/oficial/ele2026/6257/dados/${c.uf}/${c.uf}${c.code}-c0001-e006257-u.json`;const j=await json(u);if(j.f?.toLowerCase()!=='o'||j.ele!=='6257'||j.t!=='1'||j.cdabr!==c.code||!j.carg?.some(x=>x.cd==='1'))throw Error('Resultado municipal não corresponde à eleição selecionada');return j;}
async function fetchRecords(c,token,only=null){busy=true;failed=0;errors=new Map();updateStatus();const keys=only||expected();const q={items:keys.sort((a,b)=>Number(records.has(a))-Number(records.has(b))),pos:0};queue=q;let consecutive404=0,stop=false,lastPaint=0;async function worker(){while(q.pos<q.items.length&&token===run&&!stop){const key=q.items[q.pos++];const [zone,section]=key.split('-'),root=`https://resultados.tse.jus.br/oficial/ele2026/arquivo-urna/3220/dados/${c.uf}/${c.code}/${zone}/${section}`,auxUrl=`${root}/p003220-${c.uf}-m${c.code}-z${zone}-s${section}-aux.json`;try{const a=await json(auxUrl);if(a.f?.toLowerCase()!=='o')throw Error('Não oficial');const active=a.hashes.filter(h=>['recebido','totalizado'].includes(h.st.toLowerCase()));if(active.length!==1)throw Error('Boletim sem hash único ativo');const h=active[0],file=h.arq.find(x=>x.tp==='bu')?.nm;if(!/^[a-zA-Z0-9]+$/.test(h.hash)||!file||!new RegExp(`^o03220${c.uf}\\d{13}-bu\\.dat$`).test(file))throw Error('Arquivo BU inesperado');const url=`${root}/${h.hash}/${file}`,r=await controlledFetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('BU HTTP '+r.status);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>1000000)throw Error('BU excede limite');const b=parseBu(bytes,c.code,zone,section);if(token!==run)return;records.set(key,{...b,url,auxUrl,checked:new Date().toISOString()});errors.delete(key);consecutive404=0;}catch(e){if(token===run){failed++;errors.set(key,e.message||String(e));const old=records.get(key);if(old)records.set(key,{...old,stale:true});if(String(e).includes('404'))consecutive404++;else consecutive404=0;if(consecutive404>=8)stop=true;}}if(token===run&&Date.now()-lastPaint>400){lastPaint=Date.now();paint();}await new Promise(r=>setTimeout(r,150));}}
 await Promise.all(Array.from({length:8},worker));if(token!==run)return;busy=false;queue=null;paint();await saveCache(c,records);}
async function select(code){addressMarker?.remove();addressLine?.remove();addressMarker=null;addressLine=null;if(city&&records.size)await saveCache(city,records);const token=++run;busy=true;city=null;records=new Map();groups=[];queue=null;errors=new Map();openGroup=null;map.closePopup();$('nearby').hidden=true;$('matches').innerHTML='';$('localHint').textContent='';polygons.clearLayers();points.clearLayers();outline.clearLayers();$('heading').textContent='Carregando município…';$('bar').value=0;$('refresh').disabled=true;$('download').disabled=true;$('progress').textContent='Carregando locais e limite municipal…';$('validation').textContent='';try{const c=await json(`cidades/${code}.json`);const url=`https://servicodados.ibge.gov.br/api/v3/malhas/municipios/${c.ibge}?formato=application/vnd.geo+json&qualidade=minima`;const [b,m]=await Promise.all([json(url),loadMunicipal(c)]);if(token!==run)return;city=c;municipal=m;boundary=b.features?b.features[0]:b;$('boundarySource').href=url;$('city').value=`${c.name} (${c.uf.toUpperCase()})`;history.replaceState(null,'',`?municipio=${code}`);geometry();setupLocalSearch();const cache=await cached(code);if(token!==run)return;if(cache)for(const r of cache.records)records.set(r.zone+'-'+r.section,r);paint();
 if(code==='61492'){const seed=await json('semente.json');if(token!==run)return;for(const r of seed.records)if(!records.has(r.zone+'-'+r.section))records.set(r.zone+'-'+r.section,r);paint();}busy=false;paint();if(requestedLocal){const g=groups.find(g=>g.sites.some(s=>s.id===requestedLocal));requestedLocal=null;if(g){map.setView([g.lat,g.lon],16);open(g);}}
 }catch(e){if(token!==run)return;busy=false;$('progress').textContent='Não foi possível completar a consulta: '+e.message+'. Tente novamente.';$('refresh').disabled=false;}}

function addressCity(hit){const a=hit.attributes||{},uf=(a.RegionAbbr||'').toLowerCase(),name=normalize(a.City||'');const direct=lookup.find(c=>c.uf===uf&&normalize(c.name)===name);if(direct)return direct;if(uf==='df')return lookup.find(c=>c.uf==='df');if(city&&boundary&&turf.booleanPointInPolygon([hit.location.x,hit.location.y],boundary))return lookup.find(c=>c.code===city.code);return null;}
async function showAddress(hit){
 const c=addressCity(hit);if(!c){$('advancedSearch').open=true;$('addressHint').textContent='Não consegui identificar o município desse endereço. Inclua cidade e UF na busca, ou selecione o município abaixo.';return;}
 $('addressHint').textContent='Endereço encontrado. Abrindo o município e o local de votação mais próximo…';
 if(!city||city.code!==c.code)await select(c.code);if(!city||city.code!==c.code||!groups.length)throw Error('Não foi possível carregar os locais do município.');
 const lat=Number(hit.location.y),lon=Number(hit.location.x);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!turf.booleanPointInPolygon([lon,lat],boundary))throw Error('O ponto encontrado está fora do limite municipal. Confira o endereço e a cidade.');
 const box=turf.bbox(boundary),factor=Math.cos((box[1]+box[3])/2*Math.PI/180);const rank=g=>(g.lon-lon)**2*factor**2+(g.lat-lat)**2;const nearest=groups.reduce((a,b)=>rank(a)<rank(b)?a:b);
 addressMarker?.remove();addressLine?.remove();addressMarker=L.circleMarker([lat,lon],{radius:8,color:'white',weight:3,fillColor:'#1568c5',fillOpacity:1}).addTo(map).bindTooltip('Endereço pesquisado',{permanent:true,direction:'bottom'});
 addressLine=L.polyline([[lat,lon],[nearest.lat,nearest.lon]],{color:'#1568c5',weight:2,dashArray:'5 5',interactive:false}).addTo(map);
 const distance=Math.round(L.latLng(lat,lon).distanceTo(L.latLng(nearest.lat,nearest.lon)));const approx=!['PointAddress','StreetAddress','Subaddress'].includes(hit.attributes?.Addr_type);
 $('addressHint').textContent=`${hit.address}. ${approx?'Localização aproximada; o número do imóvel não foi confirmado. ':''}Local mais próximo: ${nearest.sites[0].name}, a cerca de ${nf.format(distance)} metros em linha reta. Isso não indica em qual escola você está registrado para votar.`;
 map.fitBounds(L.latLngBounds([[lat,lon],[nearest.lat,nearest.lon]]).pad(.4),{maxZoom:16,padding:[45,45]});open(nearest);
}
$('addressSearch').addEventListener('submit',async e=>{e.preventDefault();const query=$('address').value.trim();if(query.length<8){$('addressHint').textContent='Digite rua, número, cidade e UF, ou um CEP.';return;}$('addressButton').disabled=true;$('addressResults').innerHTML='';$('addressHint').textContent='Procurando o endereço…';try{
 let hits=addressMemory.get(query);if(!hits){const cfg=await json('config.json');const url=new URL(cfg.geocoder);url.search=new URLSearchParams({SingleLine:query,f:'json',outFields:'City,RegionAbbr,Addr_type,Match_addr',maxLocations:'4',sourceCountry:'BRA',forStorage:'false'});const j=await json(url.href);if(j.error)throw Error(j.error.message||'Serviço de endereço indisponível');hits=j.candidates||[];addressMemory.set(query,hits);}
 if(!hits.length){$('addressHint').textContent='Endereço não encontrado. Tente acrescentar cidade, estado ou CEP.';return;}
 if(hits.length===1&&hits[0].score>=85){await showAddress(hits[0]);return;}
 $('addressHint').textContent='Escolha o endereço correto:';for(const hit of hits){const b=document.createElement('button');b.type='button';b.textContent=hit.address;b.addEventListener('click',()=>showAddress(hit).catch(e=>$('addressHint').textContent=e.message));$('addressResults').append(b);}
 }catch(error){$('addressHint').textContent='Não consegui localizar o endereço: '+error.message+'. Tente incluir cidade e UF.';}finally{$('addressButton').disabled=false;}});

$('search').addEventListener('submit',e=>{e.preventDefault();const text=$('city').value.trim().toUpperCase();const c=lookup.find(c=>`${c.name} (${c.uf.toUpperCase()})`===text)||lookup.find(c=>c.code===text||c.ibge===text);if(c)select(c.code);else $('progress').textContent='Escolha uma cidade da lista, incluindo a UF.';});
$('refresh').addEventListener('click',()=>city&&!busy&&fetchRecords(city,run));
$('download').addEventListener('click',()=>{if(!city)return;const rows=[['municipio','uf','local','endereco','latitude','longitude','boletins_lidos','boletins_esperados','lula_votos','flavio_votos','demais_votos','validos','lula_pct','flavio_pct','status','captura_utc']];for(const s of city.sites){const r=result({sites:[s]});rows.push([city.name,city.uf.toUpperCase(),s.name,s.address,s.lat,s.lon,r.rows.length,r.keys.length,r.rows.length?(r.votes['13']||0):'',r.rows.length?(r.votes['22']||0):'',r.rows.length?r.total-(r.votes['13']||0)-(r.votes['22']||0):'',r.rows.length?r.total:'',r.total?(r.votes['13']||0)/r.total*100:'',r.total?(r.votes['22']||0)/r.total*100:'',r.complete?'BOLETINS_COMPLETOS':'PARCIAL',new Date().toISOString()]);}const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`votos-locais-${city.code}-2026.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);});
try{lookup=await json('cidades.json');$('cities').innerHTML=lookup.map(c=>`<option value="${esc(c.name)} (${c.uf.toUpperCase()})"></option>`).join('');const code=new URLSearchParams(location.search).get('municipio')||'61492';await select(lookup.some(c=>c.code===code)?code:'61492');}catch(e){$('progress').textContent='Cadastro indisponível: '+e.message;}
