#!/usr/bin/env python3
"""
Sync Lulometro dataset files to BigQuery.

This script expects local files already generated by build_lulometro_data.py:
- lulometro-dashboard/data/records.jsonl.gz
- lulometro-dashboard/data/items.json
- lulometro-dashboard/data/metadata.json
"""

from __future__ import annotations

import argparse
import datetime as dt
import gzip
import json
import os
import tempfile
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from google.api_core.exceptions import NotFound
from google.cloud import bigquery


ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT_DIR / "lulometro-dashboard" / "data"
RECORDS_GZ = DATA_DIR / "records.jsonl.gz"
ITEMS_JSON = DATA_DIR / "items.json"
META_JSON = DATA_DIR / "metadata.json"

RECORDS_TABLE = "records"
ITEMS_TABLE = "items"
RUNS_TABLE = "pipeline_runs"
VIEW_LIGHT = "records_light"
VIEW_FULL = "records_full_text"

RECORDS_SCHEMA = [
    bigquery.SchemaField("id", "STRING"),
    bigquery.SchemaField("url", "STRING"),
    bigquery.SchemaField("source", "STRING"),
    bigquery.SchemaField("type", "STRING"),
    bigquery.SchemaField("president_slug", "STRING"),
    bigquery.SchemaField("president", "STRING"),
    bigquery.SchemaField("mandate", "STRING"),
    bigquery.SchemaField("date", "DATE"),
    bigquery.SchemaField("date_source", "STRING"),
    bigquery.SchemaField("title", "STRING"),
    bigquery.SchemaField("location", "STRING"),
    bigquery.SchemaField("description", "STRING"),
    bigquery.SchemaField("text", "STRING"),
    bigquery.SchemaField("word_count", "INT64"),
    bigquery.SchemaField("updated_at", "TIMESTAMP"),
    bigquery.SchemaField("fetch_failures", "INT64"),
    bigquery.SchemaField("last_error", "STRING"),
]

ITEMS_SCHEMA = [
    bigquery.SchemaField("id", "STRING"),
    bigquery.SchemaField("url", "STRING"),
    bigquery.SchemaField("source", "STRING"),
    bigquery.SchemaField("type", "STRING"),
    bigquery.SchemaField("president_slug", "STRING"),
    bigquery.SchemaField("president", "STRING"),
    bigquery.SchemaField("mandate", "STRING"),
    bigquery.SchemaField("date", "DATE"),
    bigquery.SchemaField("title", "STRING"),
    bigquery.SchemaField("location", "STRING"),
    bigquery.SchemaField("description", "STRING"),
    bigquery.SchemaField("word_count", "INT64"),
    bigquery.SchemaField("text_length", "INT64"),
]

RUNS_SCHEMA = [
    bigquery.SchemaField("synced_at", "TIMESTAMP"),
    bigquery.SchemaField("generated_at", "TIMESTAMP"),
    bigquery.SchemaField("total_records", "INT64"),
    bigquery.SchemaField("candidate_urls", "INT64"),
    bigquery.SchemaField("new_urls", "INT64"),
    bigquery.SchemaField("detail_fetched", "INT64"),
    bigquery.SchemaField("duration_seconds", "FLOAT64"),
    bigquery.SchemaField("workflow_run_id", "STRING"),
    bigquery.SchemaField("commit_sha", "STRING"),
    bigquery.SchemaField("metadata_json", "STRING"),
]


def normalize_string(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def normalize_int(value: Any) -> Optional[int]:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def normalize_float(value: Any) -> Optional[float]:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def normalize_date(value: Any) -> Optional[str]:
    text = normalize_string(value)
    if not text:
        return None
    try:
        return dt.date.fromisoformat(text).isoformat()
    except ValueError:
        return None


def normalize_timestamp(value: Any) -> Optional[str]:
    text = normalize_string(value)
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = dt.datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.isoformat()


def read_records_rows() -> List[Dict[str, Any]]:
    if not RECORDS_GZ.exists():
        raise FileNotFoundError(f"Missing file: {RECORDS_GZ}")

    rows: List[Dict[str, Any]] = []
    with gzip.open(RECORDS_GZ, "rt", encoding="utf-8") as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw:
                continue
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue

            rows.append(
                {
                    "id": normalize_string(rec.get("id")),
                    "url": normalize_string(rec.get("url")),
                    "source": normalize_string(rec.get("source")),
                    "type": normalize_string(rec.get("type")),
                    "president_slug": normalize_string(rec.get("president_slug")),
                    "president": normalize_string(rec.get("president")),
                    "mandate": normalize_string(rec.get("mandate")),
                    "date": normalize_date(rec.get("date")),
                    "date_source": normalize_string(rec.get("date_source")),
                    "title": normalize_string(rec.get("title")),
                    "location": normalize_string(rec.get("location")),
                    "description": normalize_string(rec.get("description")),
                    "text": rec.get("text") or "",
                    "word_count": normalize_int(rec.get("word_count")),
                    "updated_at": normalize_timestamp(rec.get("updated_at")),
                    "fetch_failures": normalize_int(rec.get("fetch_failures")),
                    "last_error": normalize_string(rec.get("last_error")),
                }
            )
    return rows


def read_items_rows() -> List[Dict[str, Any]]:
    if not ITEMS_JSON.exists():
        raise FileNotFoundError(f"Missing file: {ITEMS_JSON}")
    payload = json.loads(ITEMS_JSON.read_text(encoding="utf-8"))
    items = payload.get("items") or []
    rows: List[Dict[str, Any]] = []
    for item in items:
        rows.append(
            {
                "id": normalize_string(item.get("id")),
                "url": normalize_string(item.get("url")),
                "source": normalize_string(item.get("source")),
                "type": normalize_string(item.get("type")),
                "president_slug": normalize_string(item.get("president_slug")),
                "president": normalize_string(item.get("president")),
                "mandate": normalize_string(item.get("mandate")),
                "date": normalize_date(item.get("date")),
                "title": normalize_string(item.get("title")),
                "location": normalize_string(item.get("location")),
                "description": normalize_string(item.get("description")),
                "word_count": normalize_int(item.get("word_count")),
                "text_length": normalize_int(item.get("text_length")),
            }
        )
    return rows


def read_metadata() -> Dict[str, Any]:
    if not META_JSON.exists():
        return {}
    try:
        return json.loads(META_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def ensure_dataset(client: bigquery.Client, project_id: str, dataset_id: str, location: str) -> None:
    fq_dataset = f"{project_id}.{dataset_id}"
    try:
        client.get_dataset(fq_dataset)
    except NotFound:
        ds = bigquery.Dataset(fq_dataset)
        ds.location = location
        client.create_dataset(ds)


def write_rows_temp_jsonl(rows: Iterable[Dict[str, Any]]) -> Path:
    fd, path_str = tempfile.mkstemp(prefix="lulometro_bq_", suffix=".jsonl")
    os.close(fd)
    path = Path(path_str)
    with path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
    return path


def load_json_rows(
    client: bigquery.Client,
    table_id: str,
    schema: List[bigquery.SchemaField],
    rows: List[Dict[str, Any]],
    write_disposition: str,
) -> int:
    temp_file = write_rows_temp_jsonl(rows)
    try:
        job_config = bigquery.LoadJobConfig(
            schema=schema,
            source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            write_disposition=write_disposition,
        )
        with temp_file.open("rb") as fh:
            job = client.load_table_from_file(fh, table_id, job_config=job_config)
        job.result()
        table = client.get_table(table_id)
        return int(table.num_rows or 0)
    finally:
        temp_file.unlink(missing_ok=True)


def create_or_replace_views(client: bigquery.Client, project_id: str, dataset_id: str) -> None:
    records_table = f"{project_id}.{dataset_id}.{RECORDS_TABLE}"
    view_light = f"{project_id}.{dataset_id}.{VIEW_LIGHT}"
    view_full = f"{project_id}.{dataset_id}.{VIEW_FULL}"

    client.query(
        f"""
        CREATE OR REPLACE VIEW `{view_light}` AS
        SELECT
          id,
          date,
          president,
          mandate,
          type,
          title,
          location,
          url,
          source,
          word_count
        FROM `{records_table}`
        """
    ).result()

    client.query(
        f"""
        CREATE OR REPLACE VIEW `{view_full}` AS
        SELECT
          id,
          date,
          president,
          mandate,
          type,
          title,
          location,
          url,
          source,
          word_count,
          text
        FROM `{records_table}`
        """
    ).result()


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Lulometro data to BigQuery")
    parser.add_argument("--project", default=os.getenv("BQ_PROJECT_ID", "").strip(), help="GCP project id")
    parser.add_argument("--dataset", default=os.getenv("BQ_DATASET", "").strip(), help="BigQuery dataset id")
    parser.add_argument("--location", default=os.getenv("BQ_LOCATION", "US").strip(), help="BigQuery dataset location")
    parser.add_argument("--workflow-run-id", default=os.getenv("GITHUB_RUN_ID", "").strip(), help="GitHub Actions run id")
    parser.add_argument("--commit-sha", default=os.getenv("GITHUB_SHA", "").strip(), help="Git commit sha")
    args = parser.parse_args()

    if not args.project:
        raise SystemExit("Missing --project or BQ_PROJECT_ID")
    if not args.dataset:
        raise SystemExit("Missing --dataset or BQ_DATASET")

    records_rows = read_records_rows()
    items_rows = read_items_rows()
    metadata = read_metadata()

    client = bigquery.Client(project=args.project)
    ensure_dataset(client, args.project, args.dataset, args.location or "US")

    records_table_id = f"{args.project}.{args.dataset}.{RECORDS_TABLE}"
    items_table_id = f"{args.project}.{args.dataset}.{ITEMS_TABLE}"
    runs_table_id = f"{args.project}.{args.dataset}.{RUNS_TABLE}"

    records_count = load_json_rows(
        client=client,
        table_id=records_table_id,
        schema=RECORDS_SCHEMA,
        rows=records_rows,
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
    )
    items_count = load_json_rows(
        client=client,
        table_id=items_table_id,
        schema=ITEMS_SCHEMA,
        rows=items_rows,
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
    )

    run_row = {
        "synced_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "generated_at": normalize_timestamp(metadata.get("generated_at")),
        "total_records": normalize_int(metadata.get("total_records")),
        "candidate_urls": normalize_int(metadata.get("candidate_urls")),
        "new_urls": normalize_int(metadata.get("new_urls")),
        "detail_fetched": normalize_int(metadata.get("detail_fetched")),
        "duration_seconds": normalize_float(metadata.get("duration_seconds")),
        "workflow_run_id": args.workflow_run_id or "",
        "commit_sha": args.commit_sha or "",
        "metadata_json": json.dumps(metadata, ensure_ascii=False),
    }
    load_json_rows(
        client=client,
        table_id=runs_table_id,
        schema=RUNS_SCHEMA,
        rows=[run_row],
        write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
    )

    create_or_replace_views(client, args.project, args.dataset)

    print("BigQuery sync complete.")
    print(f"Project: {args.project}")
    print(f"Dataset: {args.dataset}")
    print(f"Records loaded: {records_count}")
    print(f"Items loaded: {items_count}")
    print(f"Views updated: {VIEW_LIGHT}, {VIEW_FULL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
