import React,{useEffect,useRef,useState} from 'react';
import geometry from './brazil-map.json';
import seed from './state-results.json';
import {candidates,integer,published,refreshStateResults,StateResult} from './national-source';
const num=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR');
const percent=(v:number|null|undefined)=>v==null?'—':(v*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
export const fraction=(v:unknown)=>typeof v==='string'&&/^\d+(,\d+)?$/.test(v)?Number(v.replace(',','.'))/100:null;
export function standing(r:StateResult|undefined){const votes=r&&published(r.data)?candidates(r.data).filter(c=>c.votes!==null).sort((a,b)=>(b.votes??0)-(a.votes??0)):[];const tied=votes.length>1&&votes[0].votes===votes[1].votes;const leader=votes[0],second=votes[1];return {votes,tied,leader,second,color:!leader?'#d9dfe5':tied?'#a27c28':leader.number==='13'?'#b80000':leader.number==='22'?'#167b51':'#576f9b',margin:leader&&second?(leader.votes??0)-(second.votes??0):null,points:leader?.pct!=null&&second?.pct!=null?(leader.pct-second.pct)*100:null};}
export default function BrazilMap({onResults}:{onResults?:(r:Record<string,StateResult>)=>void}={}){
 const [results,setResults]=useState<Record<string,StateResult>>(seed),[chosen,setChosen]=useState('SP'),[updating,setUpdating]=useState(false);const last=useRef(results);last.current=results;
 useEffect(()=>{let stopped=false,busy=false;const update=async()=>{if(busy)return;busy=true;setUpdating(true);try{const fresh=await refreshStateResults(last.current,geometry.features.map(f=>f.uf));if(!stopped){setResults(fresh);onResults?.(fresh);}}finally{busy=false;if(!stopped)setUpdating(false);}};update();const timer=setInterval(update,30000);return()=>{stopped=true;clearInterval(timer);};},[]);
 const feature=geometry.features.find(f=>f.uf===chosen)!,r=results[chosen],valid=!!r&&published(r.data),d=valid?r.data:null,s=standing(r);const total=integer(d?.s?.ts),processed=integer(d?.s?.st),turnout=integer(d?.e?.c),absent=integer(d?.e?.a),votingTotal=integer(d?.v?.tv),blank=integer(d?.v?.vb),nullVotes=integer(d?.v?.tvn);const done=valid&&d.and==='f'&&integer(d.s?.snt)===0;
 const failures=Object.values(results).filter(r=>r.stale).length;
 const label=(uf:string)=>{const st=standing(results[uf]);return uf+': '+(!st.leader?'sem divulgação atual':st.tied?'empate':st.leader.name+' na frente por '+num(st.margin)+' votos')+(results[uf]?.stale?' · leitura antiga':'');};
 return <section className="national-section brazil-map-section" id="mapa-brasil"><div className="section-title"><h2>Mapa do Brasil · liderança por UF</h2><span>{updating?'Consultando resultados estaduais…':'Atualização automática · 30s'}</span></div><p className="map-instructions">Passe o mouse, toque ou use o teclado para ver os detalhes. As cores mostram a liderança no resultado disponível de cada UF.</p><div className="map-legend">{[['#b80000','Lula'],['#167b51','Flávio Bolsonaro'],['#576f9b','Outro candidato'],['#a27c28','Empate'],['#d9dfe5','Sem divulgação atual']].map(([color,name])=><span key={name}><i style={{background:color}}/>{name}</span>)}</div>
 {!!failures&&<p className="map-read-warning" role="status">Falha de consulta em {failures} UF(s). A última leitura aparece identificada nos detalhes.</p>}
 <div className="brazil-map-layout"><div className="brazil-map-canvas"><svg viewBox={geometry.viewBox} aria-label="Mapa interativo dos 26 estados e do Distrito Federal"><g>{geometry.features.map(f=><path key={f.uf} d={f.path} fill={standing(results[f.uf]).color} fillRule="evenodd" className={'map-state '+(chosen===f.uf?'selected':'')+(results[f.uf]?.stale?' stale':'')} data-uf={f.uf} role="button" tabIndex={0} aria-label={label(f.uf)} aria-pressed={chosen===f.uf} onPointerEnter={()=>setChosen(f.uf)} onFocus={()=>setChosen(f.uf)} onClick={()=>setChosen(f.uf)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setChosen(f.uf);}}}><title>{label(f.uf)}</title></path>)}</g><g className="map-labels">{geometry.features.map(f=><g key={f.uf}>{f.callout&&<line x1={f.cx} y1={f.cy} x2={f.x} y2={f.y} className="map-callout"/>}<text x={f.x} y={f.y} className={f.callout?'outside-label':''} textAnchor="middle" dominantBaseline="middle">{f.uf}</text></g>)}</g><circle className="map-df" cx={geometry.features.find(f=>f.uf==='DF')!.cx} cy={geometry.features.find(f=>f.uf==='DF')!.cy} r="6" fill={standing(results.DF).color} onPointerEnter={()=>setChosen('DF')} onClick={()=>setChosen('DF')}><title>{label('DF')}</title></circle></svg></div>
 <aside className="map-detail" aria-label="Detalhes do estado selecionado"><label className="map-select">Estado<select aria-label="Estado no mapa" value={chosen} onChange={e=>setChosen(e.target.value)}>{[...geometry.features].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(f=><option key={f.uf} value={f.uf}>{f.name} ({f.uf})</option>)}</select></label><div className="map-detail-title"><h3>{feature.name} <small>{chosen}</small></h3><span className={done?'map-done':'map-partial'}>{done?'Concluído':valid?'Parcial':'Sem divulgação atual'}</span></div>
 {r?.stale&&<p className="map-read-warning">LEITURA ANTIGA · consulta falhou: {r.error}</p>}
 <div className="map-lead" style={{borderColor:s.color}}><strong>{!s.leader?'Sem liderança disponível':s.tied?'Empate na primeira posição':s.leader.name+' na frente'}</strong>{s.leader&&s.second&&!s.tied&&<p>Vantagem de <b>{num(s.margin)} votos</b> e <b>{s.points==null?'—':s.points.toLocaleString('pt-BR',{maximumFractionDigits:2})} pontos percentuais</b> sobre {s.second.name}.</p>}</div>
 <div className="map-coverage"><b>{percent(total&&processed!==null?processed/total:null)} das seções totalizadas</b><div className="coverage-bar"><div style={{width:Math.min(100,total&&processed!==null?100*processed/total:0)+'%'}}/></div><small>{num(processed)} de {num(total)} · {num(total!==null&&processed!==null?total-processed:null)} ainda não totalizadas</small></div>
 <div className="map-votes-scroll"><table className="map-votes"><caption>Votos por candidato nesta UF</caption><thead><tr><th>Candidato</th><th>Votos</th><th>% TSE</th></tr></thead><tbody>{s.votes.map(c=><tr key={c.number}><th>{c.name}<small>{c.number} · {c.party}</small></th><td>{num(c.votes)}</td><td>{percent(c.pct)}</td></tr>)}</tbody></table></div>
 <dl className="map-other"><div><dt>Abstenção nas seções apuradas</dt><dd>{percent(fraction(d?.e?.pan))} <small>{num(absent)} ausentes</small></dd></div><div><dt>Comparecimento já informado</dt><dd>{num(turnout)} <small>{percent(fraction(d?.e?.pc))}</small></dd></div><div><dt>Brancos</dt><dd>{num(blank)} <small>{percent(votingTotal&&blank!==null?blank/votingTotal:null)} dos votos</small></dd></div><div><dt>Nulos</dt><dd>{num(nullVotes)} <small>{percent(votingTotal&&nullVotes!==null?nullVotes/votingTotal:null)} dos votos</small></dd></div></dl>
 <p className="freshness">Arquivo da UF: {r?.data?r.data.dg+' '+r.data.hg:'indisponível'} · horário literal do TSE.<br/>{r&&<a href={r.source} target="_blank" rel="noreferrer">Abrir JSON oficial desta UF ↗</a>}</p></aside></div>
 <p className="aside-intro">Liderança parcial pode mudar. Percentuais dos candidatos usam os votos a candidatos concorrentes, conforme o TSE. Brancos e nulos usam o total de votos; a abstenção usa o eleitorado das seções apuradas. Cada UF pode ter um horário de geração diferente. <a href={geometry.source} target="_blank" rel="noreferrer">Malha geográfica: IBGE ↗</a></p></section>;
}
