import React,{useState,useEffect,useCallback,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import initial from './national-snapshot.json';
import {Snapshot,BASE,RESULT,INDEX,published,candidates,integer,refreshNational,refreshHeadline} from './national-source';
const initialData={...initial,municipal:initial.municipal.map((m:any[])=>({code:m[0],ibge:m[1],name:m[2],uf:m[3],sections:m[4],electorate:m[5],religionAvailable:m[6],source:BASE+'/dados/'+m[3].toLowerCase()+'/'+m[3].toLowerCase()+m[0]+'-c0001-e006257-u.json',indexSource:BASE+'/dados/'+m[3].toLowerCase()+'/'+m[3].toLowerCase()+'-e006257-ab.json',generated:initial.municipalGeneration,status:'Sem divulgação atual',processed:null,turnout:null,valid:null,blank:null,nullVotes:null,votes:[],...(m[7]?{generated:m[7][0],status:m[7][1],processed:m[7][2],turnout:m[7][3],valid:m[7][4],blank:m[7][5],nullVotes:m[7][6],votes:m[7][7].map((v:any[])=>({...candidates(initial.national).find(c=>c.number===v[0]),number:v[0],votes:v[1],pct:v[2]}))}:{})}))} as unknown as Snapshot;
const n=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR');const pct=(v:number|null|undefined)=>v==null?'—':(100*v).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
const dateKey=(s:string)=>{const [d,t='']=s.split(' ');return d.split('/').reverse().join('')+t;};
const fold=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function download(name:string,text:string){const u=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function National(){
 const [data,setData]=useState(initialData),[loading,setLoading]=useState(false),[uf,setUf]=useState('Todas'),[query,setQuery]=useState(''),[status,setStatus]=useState('Todos'),[order,setOrder]=useState('Município'),[page,setPage]=useState(0),[selected,setSelected]=useState<string|null>(null),[text,setText]=useState(''),[edited,setEdited]=useState(false),[copied,setCopied]=useState(false);const flight=useRef(false);
 const refresh=useCallback(async()=>{if(flight.current)return;flight.current=true;setLoading(true);try{setData(old=>old);const updated=await refreshNational(data);setData(old=>({...updated,national:dateKey(old.national.dg+' '+old.national.hg)>dateKey(updated.national.dg+' '+updated.national.hg)?old.national:updated.national}));}finally{setLoading(false);flight.current=false;}},[data]);const latest=useRef(refresh);latest.current=refresh;
 useEffect(()=>{let stopped=false,headlineBusy=false;const headline=async()=>{if(headlineBusy)return;headlineBusy=true;try{const fresh=await refreshHeadline();if(!stopped)setData(old=>({...old,...fresh}));}catch(e){if(!stopped)setData(old=>({...old,errors:[...old.errors.filter(e=>!e.startsWith('Resumo nacional:')),'Resumo nacional: '+(e as Error).message]}));}finally{headlineBusy=false;}};headline();latest.current();const timer=setInterval(()=>{headline();latest.current();},30000);return()=>{stopped=true;clearInterval(timer);};},[]);
 const current=published(data.national),votes=candidates(data.national).sort((a,b)=>(b.votes??0)-(a.votes??0)),allCandidates=[...votes].sort((a,b)=>Number(a.number)-Number(b.number));
 const total=current?integer(data.national.s?.ts):null,processed=current?integer(data.national.s?.st):null,turnout=current?integer(data.national.e?.c):null;const complete=current&&data.national.and==='f'&&integer(data.national.s?.snt)===0;
 const shown=data.municipal.filter(m=>(uf==='Todas'||m.uf===uf)&&(status==='Todos'||m.status===status)&&fold(m.name+' '+m.ibge+' '+m.code).includes(fold(query))).sort((a,b)=>order==='Mais recentes'?dateKey(b.generated).localeCompare(dateKey(a.generated))||a.name.localeCompare(b.name,'pt-BR'):order==='Maior eleitorado'?(b.electorate??0)-(a.electorate??0):a.name.localeCompare(b.name,'pt-BR'));const visible=shown.slice(page*50,page*50+50);
 useEffect(()=>setPage(0),[uf,query,status,order]);
 const stamp=data.national.dg+' '+data.national.hg;const summary=current?`Resultado nacional de presidente, primeiro turno de 2026. Arquivo do TSE gerado em ${stamp}, horário literal da fonte. ${n(turnout)} eleitores com comparecimento registrado; ${n(processed)} de ${n(total)} seções totalizadas (${pct(total&&processed!==null?processed/total:null)}). ${complete?'Totalização concluída.':'Resultado parcial; a liderança pode mudar.'}\n\n${votes.map(v=>`${v.name} (${v.number}): ${n(v.votes)} votos (${pct(v.pct)} dos votos a candidatos concorrentes, conforme o TSE).`).join('\n')}\n\nFonte: ${RESULT}`:`O arquivo nacional do TSE disponível foi gerado em ${stamp}, antes da votação de 04/10/2026. Ainda não há divulgação atual validada nesta consulta. Votos indisponíveis não são zero votos.\nFonte: ${RESULT}`;
 useEffect(()=>{if(!edited)setText(summary);},[summary,edited]);
 function exportCsv(){const header=['UF','Municipio','IBGE','TSE','Situacao','Secoes totalizadas','Secoes previstas','Percentual totalizado','Eleitorado','Comparecimento','Validos','Brancos','Nulos',...allCandidates.flatMap(v=>[v.name+' votos',v.name+' percentual TSE']),'Arquivo gerado','Fonte','Leitura antiga'];const rows=shown.map(m=>[m.uf,m.name,m.ibge,m.code,m.status,m.processed,m.sections,m.processed!==null&&m.sections?m.processed/m.sections:null,m.electorate,m.turnout,m.valid,m.blank,m.nullVotes,...allCandidates.flatMap(v=>{const c=m.votes.find(c=>c.number===v.number);return[c?.votes??null,c?.pct??null];}),m.generated,m.source,m.stale?'Sim':'Não']);const esc=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';download('resultados-municipais-tse-2026.csv',[header,...rows].map(r=>r.map(esc).join(';')).join('\r\n'));}
 const active=data.municipal.find(m=>m.code===selected);const coverage=(s:any)=>s.processed!==null&&s.sections?s.processed/s.sections:null;
 return <><header className="masthead"><div className="brand"><strong>Eleições 2026</strong></div><nav className="site-nav"><a href="../">Exterior</a><a href="./" aria-current="page">Nacional</a><a href={data.sheetUrl} target="_blank" rel="noreferrer">Google Sheets ↗</a></nav></header><main className="dashboard national">
 <div className="title-row"><div><div className="eyebrow">PRESIDENTE · PRIMEIRO TURNO · 4 OUT 2026</div><h1>Resultados nacionais</h1></div><button className="action" onClick={()=>latest.current()} disabled={loading}>{loading?'Consultando TSE…':'Atualizar agora'}</button></div>
 <p className="freshness">Consulta: {new Date(data.checkedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} BRT · atualização automática a cada 30s enquanto a página estiver aberta.</p>
 {!!data.errors.length&&<div className="warning" role="status">Algumas fontes não puderam ser atualizadas. A última leitura permanece identificada.<details><summary>Falhas de consulta ({data.errors.length})</summary>{data.errors.map((e,i)=><p key={i}>{e}</p>)}</details></div>}
 {!current&&<div className="warning" role="status">Sem divulgação nacional atual validada. O arquivo disponível foi gerado em <b>{stamp}</b>, antes da votação. Os votos permanecem indisponíveis.</div>}
 <section className="metrics"><div><span>SEÇÕES TOTALIZADAS</span><strong>{pct(total&&processed!==null?processed/total:null)}</strong><p>{current?n(processed)+' de '+n(total)+' · '+(complete?'concluído':'parcial'):'Aguardando divulgação atual'}</p></div><div><span>COMPARECIMENTO NOS DADOS</span><strong>{n(turnout)}</strong><p>Eleitores nas seções já totalizadas</p></div><div><span>LULA · 13</span><strong>{n(votes.find(v=>v.number==='13')?.votes)}</strong><p>{pct(votes.find(v=>v.number==='13')?.pct)} dos votos concorrentes</p></div><div><span>FLAVIO BOLSONARO · 22</span><strong>{n(votes.find(v=>v.number==='22')?.votes)}</strong><p>{pct(votes.find(v=>v.number==='22')?.pct)} dos votos concorrentes</p></div><div><span>ABSTENÇÃO ATÉ AGORA</span><strong>{current?pct(Number(data.national.e?.pan?.replace(",","."))/100):"—"}</strong><p>{current?n(integer(data.national.e?.a)):"—"} ausentes · parcial nas seções apuradas</p></div></section>
 <section className="national-section"><div className="section-title"><h2>Votos por candidato · Brasil</h2><span>{complete?'Concluído':current?'Parcial':'Sem divulgação atual'}</span></div><div className="candidate-grid">{votes.map(v=><div key={v.number} className="national-candidate"><div><b>{v.name}</b><span>{v.number} · {v.party}</span></div><strong>{n(v.votes)}<small> votos · {pct(v.pct)}</small></strong><div className="coverage-bar"><div style={{width:Math.min(100,(v.pct??0)*100)+'%',background:v.number==='13'?'#b80000':v.number==='22'?'#167b51':'#637282'}}/></div></div>)}</div><p className="aside-intro">Percentuais por candidato fornecidos pelo TSE sobre os votos a candidatos concorrentes. Brancos e nulos ficam fora desse denominador. Cobertura de seções não é uma probabilidade de vitória.</p><p className="freshness">Arquivo nacional: {stamp} · <a href={RESULT} target="_blank" rel="noreferrer">Abrir JSON oficial ↗</a></p></section>
 <section className="national-section"><div className="section-title"><h2>Andamento por UF</h2><span>Brasil inclui a abrangência exterior do TSE</span></div><div className="state-grid">{data.states.map(s=><button className={'state '+(s.status==='Concluído'?'done':'')} key={s.uf} disabled={s.uf==='ZZ'} onClick={()=>{setUf(s.uf);document.getElementById('municipal')?.scrollIntoView({behavior:'smooth'});}}><div><b>{s.uf}</b><span>{pct(coverage(s))}</span></div><div className="coverage-bar"><div style={{width:Math.min(100,(coverage(s)??0)*100)+'%'}}/></div><small>{s.status} · {s.processed===null?n(s.sections)+' seções previstas':n(s.processed)+' / '+n(s.sections)}</small></button>)}</div></section>
 <section className="national-section" id="municipal"><div className="section-title"><h2>Resultados por município</h2><span>{n(shown.length)} municípios</span></div><div className="national-tools"><label>UF<select value={uf} onChange={e=>setUf(e.target.value)}>{['Todas',...Array.from(new Set(data.municipal.map(m=>m.uf))).sort()].map(s=><option key={s}>{s}</option>)}</select></label><label>Município ou código<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar município"/></label><label>Situação<select value={status} onChange={e=>setStatus(e.target.value)}>{['Todos','Parcial','Concluído','Sem divulgação atual'].map(s=><option key={s}>{s}</option>)}</select></label><label>Ordenar<select value={order} onChange={e=>setOrder(e.target.value)}>{['Município','Mais recentes','Maior eleitorado'].map(s=><option key={s}>{s}</option>)}</select></label><button className="action" onClick={()=>{setUf('Todas');setQuery('');setStatus('Todos');setOrder('Município');}}>Limpar filtros</button><button className="action" onClick={exportCsv}>Baixar CSV filtrado</button></div>
 <div className="ranking-scroll"><table className="municipal-table"><thead><tr><th>Município / UF</th><th>Situação / cobertura</th><th>Comparecimento</th>{allCandidates.map(v=><th key={v.number}>{v.name}<br/>Votos · % TSE</th>)}<th>Arquivo gerado</th><th>Fonte</th></tr></thead><tbody>{visible.map(m=><tr className={m.status==='Concluído'?'done':''} key={m.code}><td><button className="municipal-name" onClick={()=>setSelected(m.code)}>{m.name} / {m.uf}</button><small>IBGE {m.ibge} · TSE {m.code}</small></td><td>{m.status}{m.stale?' · LEITURA ANTIGA':''}<div className="coverage-bar"><div style={{width:Math.min(100,(coverage(m)??0)*100)+'%'}}/></div><small>{pct(coverage(m))} · {m.processed===null?n(m.sections)+' previstas':n(m.processed)+' de '+n(m.sections)}</small></td><td>{n(m.turnout)}</td>{allCandidates.map(v=>{const c=m.votes.find(c=>c.number===v.number);return <td key={v.number}>{n(c?.votes)}<small>{pct(c?.pct)}</small></td>})}<td>{m.generated}<small>{m.votes.length?'resultado municipal':'índice de acompanhamento da UF'}</small></td><td><a href={m.source} target="_blank" rel="noreferrer">JSON TSE ↗</a></td></tr>)}</tbody></table></div>{!shown.length&&<p className="empty">Nenhum município para esses filtros.</p>}<div className="pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{shown.length?`Página ${page+1} de ${Math.ceil(shown.length/50)}`:'Sem registros'}</span><button disabled={(page+1)*50>=shown.length} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></section>
 <section className="national-section"><div className="section-title"><h2>Planilha municipal e religião</h2><a className="action" href={data.sheetUrl} target="_blank" rel="noreferrer">Abrir Google Sheets ↗</a></div><p>Planilha separada com resultados municipais, religião do IBGE e conferência independente da tabela da Thais. Religião: Censo 2022, amostra, pessoas de 10 anos ou mais, tabela SIDRA 9537.</p><p>{data.religionSummary?.countDifferences===0?'As contagens da tabela da Thais coincidem com a extração independente nos 5.570 municípios.':`Há ${data.religionSummary?.countDifferences??'diferenças a conferir'} diferenças de contagem registradas na planilha.`} {data.religionSummary?.roundingNote}</p><p className="aside-intro">A planilha é uma fotografia da extração indicada na aba Resumo. A página consulta o TSE automaticamente; alterações na página não atualizam a planilha. Municípios criados após 2022 ficam sem dado próprio de religião de 2022.</p><a href="https://sidra.ibge.gov.br/tabela/9537" target="_blank" rel="noreferrer">Fonte independente: IBGE / SIDRA ↗</a></section>
 <section className="national-section"><div className="section-title"><h2>Texto para copiar e enviar</h2><button className="action" onClick={()=>{setEdited(false);setText(summary);}}>Refazer com dados atuais</button></div><textarea aria-label="Texto editável dos resultados nacionais" value={text} onChange={e=>{setEdited(true);setText(e.target.value);}}/><div className="national-tools"><button className="action" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{document.querySelector<HTMLTextAreaElement>('textarea')?.select();}}}>{copied?'Copiado':'Copiar texto'}</button><button className="action" onClick={()=>download('resumo-nacional-tse-2026.txt',text)}>Baixar texto</button></div></section>
 <footer>Fontes oficiais: <a href={INDEX} target="_blank" rel="noreferrer">Acompanhamento nacional do TSE ↗</a> · <a href="https://www.tse.jus.br/eleicoes/informacoes-tecnicas-sobre-a-divulgacao-de-resultados" target="_blank" rel="noreferrer">Documentação de 2026 ↗</a><p>As abrangências Brasil, UF e município não são somadas entre si. Boletins do exterior permanecem na página Exterior; o resumo nacional usa a totalização nacional publicada pelo TSE.</p></footer>
 {active&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="municipal-detail" role="dialog" aria-modal="true" aria-label={'Dados de '+active.name} onClick={e=>e.stopPropagation()}><button className="action" onClick={()=>setSelected(null)}>Fechar</button><h2>{active.name} / {active.uf}</h2><p>IBGE {active.ibge} · TSE {active.code}</p><p>{active.status} · {pct(coverage(active))} de seções totalizadas</p><p>Eleitorado: {n(active.electorate)} · comparecimento nos dados: {n(active.turnout)}</p><p>Votos válidos: {n(active.valid)} · brancos: {n(active.blank)} · nulos: {n(active.nullVotes)}</p><p>Religião do Censo 2022: {active.religionAvailable?'disponível na aba da planilha':'sem dado municipal próprio no Censo 2022'}</p><p>Arquivo: {active.generated}</p><a href={active.source} target="_blank" rel="noreferrer">Abrir resultado oficial ↗</a></section></div>}
 </main></>;
}
createRoot(document.getElementById('root')!).render(<National/>);
