'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import initialCountries from './initial-countries.json';
import Overview from './Overview';
import {Radio,Clock3,Copy,ChevronDown,RefreshCw,Search,ExternalLink,Check} from 'lucide-react';
type Vote={number?:string;name:string;votes:number;pct:number|null;party?:string};
type Country={turnout:number|null;abstention:number|null;coveredElectorate:number|null;pendingElectorate:number|null;blank:number|null;nullVotes:number|null;publishedAt:string|null;country:string;active:boolean;electorate:number|null;closeAt:string|null;firstCloseAt:string|null;processed:number;expected:number;pct:number|null;received:number;buExpected:number;buPct:number|null;buComplete:boolean;votes:Vote[];complete:boolean;tie:boolean;source:string;status:string;stale:boolean;checkedAt:string;warnings:string[];cities:{name:string;url:string;processed:number;expected:number;received:number;buExpected:number;files:{url:string;auxUrl:string;section:string;generated:string;auxGenerated:string}[]}[]};
type Data={totalizationAvailable:boolean;checkedAt:string;tseAt:string;tseStale:boolean;generated:string;countries:Country[];errors:string[];indexUrl:string};
const number=(v:number)=>v.toLocaleString('pt-BR');const percent=(v:number|null)=>v===null?'—':v.toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
const time=(v:string|number,zone='America/Sao_Paulo',seconds=false)=>new Date(v).toLocaleTimeString('pt-BR',{timeZone:zone,hour:'2-digit',minute:'2-digit',...(seconds?{second:'2-digit'}:{})});
const fold=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const color=(name:string)=>fold(name).includes('lula')?'#b80000':fold(name).includes('flavio')?'#167b51':'#526477';
const buDate=(v:string)=>v.slice(6,8)+'/'+v.slice(4,6)+'/'+v.slice(0,4)+' '+v.slice(9,11)+':'+v.slice(11,13)+':'+v.slice(13,15);
function sentence(c:Country){const v=c.votes[0];if(!v)return c.country+': aguardando resultado na fonte do TSE.';const bu=c.source==='BU TSE';return `${c.country}: ${c.tie?'há empate na liderança':v.name+' '+(c.complete?'foi o mais votado':bu?'lidera nos boletins disponíveis':'lidera a apuração parcial')}, com ${number(v.votes)} votos (${percent(v.pct)}). ${bu?'Boletins do TSE: '+c.received+'/'+c.buExpected+' seções ('+percent(c.buPct)+'). '+(c.buComplete?'Todos os boletins disponíveis; totalização ainda não confirmada.':'Cobertura parcial; não é resultado concluído.'):'TSE: '+percent(c.pct)+' das seções totalizadas ('+c.processed+'/'+c.expected+').'} Consulta: ${time(c.checkedAt,'America/Sao_Paulo',true)} de Brasília.${c.stale?' ATENÇÃO: leitura antiga.':''}${c.warnings.length?' Atenção: '+c.warnings.join(' '):''}`;}
function Coverage({country:c}:{country:Country}){
 const bu=c.source==='BU TSE',received=bu?c.received:c.processed,expected=bu?c.buExpected:c.expected;
 if(!c.votes.length||!expected||!received)return <div className="coverage-summary waiting"><strong>Aguardando dados do TSE</strong><div className="coverage-bar"><div/></div><p>{expected?number(expected)+' seções aguardando boletim ou totalização.':'Cobertura ainda sem dados nesta leitura.'}</p>{c.electorate!==null&&<p>{number(c.electorate)} eleitores cadastrados · comparecimento ainda desconhecido.</p>}</div>;
 const missing=Math.max(0,expected-received),coverage=100*received/expected;
 const message=c.stale?'Leitura antiga: aguarde nova conferência no TSE.':c.complete?'Totalização concluída no TSE.':missing?'Resultado parcial: a liderança pode mudar enquanto faltarem urnas.':bu?'Todos os boletins previstos disponíveis. Aguarda confirmação na totalização do TSE.':'Todas as seções têm dados, mas o TSE ainda não confirmou a conclusão.';
 return <div className={'coverage-summary '+(c.stale?'old':c.complete?'done':missing?'partial':'all-bus')}><div><span>{bu?'URNAS COM BOLETIM':'URNAS TOTALIZADAS · TSE'}</span><strong>{percent(coverage)}</strong></div><div className="coverage-bar" role="progressbar" aria-label={'Cobertura de '+c.country} aria-valuemin={0} aria-valuemax={100} aria-valuenow={coverage}><div style={{width:Math.min(100,coverage)+'%'}}/></div><p><b>{number(received)} de {number(expected)} seções</b>{missing?' · faltam '+number(missing):' · nenhuma seção faltando'}</p><div className="country-turnout"><div><span>Já votaram · nos dados</span><b>{c.turnout===null?'—':number(c.turnout)}</b></div><div><span>Eleitores aguardando dados</span><b>{c.pendingElectorate===null?'—':number(c.pendingElectorate)}</b></div><div><span>Abstenções registradas</span><b>{c.abstention===null?'—':number(c.abstention)}</b></div></div><p>{message}</p></div>;
}
export default function Page(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[lastPoll,setLastPoll]=useState(0),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[expanded,setExpanded]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null);
 const inFlight=useRef(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setLoading(true);try{const r=await fetch('/api/live',{cache:'no-store'});if(!r.ok)throw new Error('Não foi possível atualizar. A última leitura permanece na tela.');setData(await r.json());setError('');setLastPoll(Date.now());}catch(e){setError(e instanceof Error?e.message:'Falha de conexão');}finally{inFlight.current=false;setLoading(false);}},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[refresh]);
 async function copy(c:Country){try{await navigator.clipboard.writeText(sentence(c));setCopied(c.country);setTimeout(()=>setCopied(null),2000);}catch{setExpanded(c.country);}}
 const masthead=<header className="masthead"><div className="brand"><strong>Eleições no exterior</strong></div><div className="edition"><Radio size={15}/> ELEIÇÕES 2026 <span> / RESULTADOS AO VIVO</span></div></header>;
 const countries=data?.countries.filter(c=>c.active)??initialCountries as unknown as Country[];const available=countries.filter(c=>c.votes.length);const processed=countries.reduce((s,c)=>s+c.processed,0),expected=countries.reduce((s,c)=>s+c.expected,0);
 const buReceived=countries.reduce((sum,c)=>sum+(c.received??0),0),buExpected=countries.reduce((sum,c)=>sum+(c.buExpected??0),0);
 const ranking=countries.filter(c=>c.electorate!==null&&c.electorate!==undefined).sort((a,b)=>b.electorate!-a.electorate!);const totalElectorate=ranking.reduce((sum,c)=>sum+c.electorate!,0);
 const closed=countries.filter(c=>c.closeAt&&Date.parse(c.closeAt)<=now);
 const upcoming=countries.filter(c=>c.closeAt&&Date.parse(c.closeAt)>now).sort((a,b)=>Date.parse(a.closeAt!)-Date.parse(b.closeAt!));const next=upcoming[0];
 const shown=countries.filter(c=>(filter==='Todos'||filter==='Disponíveis'&&c.votes.length||filter==='Mais recentes'&&c.votes.length&&c.publishedAt||filter==='Encerrados'&&c.closeAt&&Date.parse(c.closeAt)<=now||filter==='BU completos'&&c.buComplete||filter==='Concluídos'&&c.complete)&&fold(c.country).includes(fold(query))).sort((a,b)=>filter==='Mais recentes'?(Date.parse(b.publishedAt!)-Date.parse(a.publishedAt!)||a.country.localeCompare(b.country,'pt-BR')):(Number(b.complete)-Number(a.complete)||Number(!!b.votes.length)-Number(!!a.votes.length)||a.country.localeCompare(b.country,'pt-BR')));
 return <>{masthead}<main className="dashboard"><div className="title-row"><div><div className="eyebrow">PRESIDENTE · PRIMEIRO TURNO · 4 OUT 2026</div><h1>Votação no exterior</h1></div><div className="clocks"><div><span>BRASÍLIA</span><strong>{time(now,'America/Sao_Paulo',true)}</strong></div><div><span>LONDRES</span><strong>{time(now,'Europe/London',true)}</strong></div></div></div>
 <div className="sync"><span className={'pulse '+(error?'bad':'')}/><strong>{loading?'Consultando fontes…':'Atualização automática · 5s'}</strong><span>Última consulta TSE: {data?time(data.tseAt,'America/Sao_Paulo',true):'—'}{data?.tseStale?' · LEITURA ANTIGA':''}</span><button onClick={refresh} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/>{loading?'Atualizando':`Atualizar · ${Math.max(0,5-Math.floor((now-lastPoll)/1000))}s`}</button></div>
 {(error||data?.errors.length)?<div className="warning" role="status">{error||'Algumas consultas ao TSE falharam. Os horários permanecem visíveis; confira o aviso de leitura antiga nos resultados.'}{data?.errors.length?<details><summary>Ver detalhes da consulta</summary>{data.errors.map(x=><div key={x}>{x}</div>)}</details>:null}</div>:null}
 <Overview countries={countries} loaded={!!data}/>
 <section className="metrics"><div><span>PAÍSES COM DADOS</span><strong>{data?available.length:'—'}<small> / {countries.length}</small></strong><p>Boletins e totalização do TSE</p></div><div><span>URNAS COM BOLETIM · EXTERIOR</span><strong>{percent(data&&buExpected&&buReceived?100*buReceived/buExpected:null)}</strong><p>{data?number(buReceived)+' de '+number(buExpected)+' seções com BU nesta leitura':'Consultando boletins…'}<br/>{data?countries.filter(c=>c.buComplete).length+' países com todos os BUs':''}</p></div><div><span>URNAS APURADAS · TSE</span><strong>{percent(data?.totalizationAvailable&&expected?processed/expected*100:null)}</strong><p>{data?.totalizationAvailable?number(processed)+' de '+number(expected)+' seções':'Totalização ainda sem divulgação'}</p></div><div><span>PRÓXIMO ENCERRAMENTO</span><strong>{next?time(next.closeAt!):'—'}<small> BRT</small></strong><p>{next?upcoming.filter(c=>c.closeAt===next.closeAt).length+' países / territórios':'Sem próximos horários'}</p></div></section>
 <div className="source-note"><strong>Fonte: TSE.</strong> Cobertura = seções com dados ÷ seções previstas. Seções agregadas entram apenas pela principal. Esse percentual não é uma probabilidade de vitória. Boletins de urna mostram votos antes da divulgação da totalização. “BU completo” significa que todas as seções têm boletim disponível. “Concluído” exige confirmação na totalização do TSE.</div>
 <section className="electorate-ranking"><div className="section-title"><h2>Onde há mais eleitores</h2><span>{number(totalElectorate)} no exterior</span></div><p className="aside-intro">Ranking por eleitorado cadastrado no TSE, separado dos votos apurados. A liderança considera apenas os dados disponíveis e pode ser parcial.</p>{!data?<p className="empty">Consultando eleitorado no TSE…</p>:<div className="ranking-scroll"><table><thead><tr><th>Posição / país</th><th>Eleitores</th><th>% do exterior</th><th>Resultado disponível</th></tr></thead><tbody>{ranking.map((c,i)=><tr key={c.country}><td>{i+1}. {c.country}</td><td>{number(c.electorate!)}</td><td>{percent(totalElectorate?100*c.electorate!/totalElectorate:null)}</td><td>{c.votes.length?(c.tie?'Empate':c.votes[0].name)+' · '+percent(c.votes[0].pct)+' · '+(c.complete?'concluído':c.source==='BU TSE'?'BU '+c.received+'/'+c.buExpected:'parcial'):'Aguardando dados'}</td></tr>)}</tbody></table></div>}</section>
 <div className="workspace"><section className="results"><div className="section-title"><h2>Resultados por país</h2><span>{shown.length} na lista</span></div><div className="tools"><div className="tabs" role="group" aria-label="Filtrar países e situação">{['Todos','Disponíveis','Mais recentes','Encerrados','BU completos','Concluídos'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)} aria-pressed={filter===f}>{f}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Buscar país" aria-label="Buscar país" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {filter==='Mais recentes'&&<p className="aside-intro">Mais novos primeiro, pelo horário de publicação do arquivo no TSE.</p>}
 {!data?<div className="empty">Consultando a API do TSE…</div>:!shown.length?<div className="empty">Nenhum resultado para este filtro. A consulta continua a cada 5 segundos.</div>:shown.map(c=>{const lead=c.votes[0],isOpen=expanded===c.country;return <article key={c.country} className={'country '+(c.complete?'complete':c.buComplete?'bus-complete':'')}><div className="country-top"><button className="country-toggle" onClick={()=>setExpanded(isOpen?null:c.country)} aria-expanded={isOpen}><h3>{c.country}</h3><ChevronDown size={18} className={isOpen?'rotated':''}/></button><span className="badge official">{c.source==='BU TSE'?'BOLETIM TSE':'TOTALIZAÇÃO TSE'}</span></div><div className="result-row"><div className="leader"><span className="status">{c.closeAt&&Date.parse(c.closeAt)<=now?'Votação encerrada (horário previsto) · ':''}{c.status}{c.stale?' · LEITURA ANTIGA':''}</span>{lead?<><strong style={{color:color(lead.name)}}>{c.tie?'Empate':lead.name}</strong><span>{number(lead.votes)} votos{lead.party?' · '+lead.party:''}</span></>:<strong className="awaiting">Aguardando boletins ou totalização</strong>}</div>{lead&&<div className="share" style={{color:color(lead.name)}}><strong>{percent(lead.pct)}</strong><span>{'dos votos nominais'}</span></div>}</div><Coverage country={c}/>{c.votes.length>0&&<table className="candidate-votes"><thead><tr><th>Candidato</th><th>Votos</th><th>%</th></tr></thead><tbody>{c.votes.map(v=><tr key={v.name}><td><i style={{background:color(v.name)}}/>{v.name}</td><td>{number(v.votes)}</td><td>{percent(v.pct)}</td></tr>)}</tbody></table>}{c.warnings.map(w=><p className="card-warning" key={w}>{w}</p>)}<div className="card-bottom"><span>{c.publishedAt&&<>Último arquivo TSE: {new Date(c.publishedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} BRT<br/></>}Fonte consultada às {time(c.checkedAt,'America/Sao_Paulo',true)} BRT</span>{lead&&<button className="copy" onClick={()=>copy(c)}>{copied===c.country?<Check size={14}/>:<Copy size={14}/>} {copied===c.country?'Copiado':'Copiar para a live'}</button>}</div>{isOpen&&<div className="expanded"><div className="city-list"><strong>Municípios e arquivos oficiais do TSE</strong>{c.cities.map(city=><div key={city.name}><a href={city.url} target="_blank" rel="noreferrer"><span>{city.name} <ExternalLink size={12}/></span><span>{c.source==='BU TSE'?city.received+'/'+city.buExpected+' BUs':city.processed+'/'+city.expected+' totalizadas'}</span></a>{city.files?.length>0&&<details><summary>Boletins oficiais por seção ({city.files.length})</summary>{city.files.map(f=><div key={f.section} className="bu-file"><a href={f.url} target="_blank" rel="noreferrer">Seção {f.section} · BU binário</a><span>Gerado: {buDate(f.generated)} · relógio da urna</span><a href={f.auxUrl} target="_blank" rel="noreferrer">Recepção TSE: arquivo gerado {f.auxGenerated}</a></div>)}</details>}</div>)}</div><div className="live-copy">{sentence(c)}</div></div>}</article>;})}</section>
 <aside><div className="section-title"><h2><Clock3 size={19}/> Próximos a fechar</h2><span>BRT</span></div><p className="aside-intro">Previsão de encerramento, não de publicação. Horário local de votação convertido para Brasília.</p><div className="schedule">{upcoming.map((c,i)=><div key={c.country} className={'schedule-row '+(!i?'next':'')}><div className="schedule-time"><strong>{time(c.closeAt!)}</strong><span>{time(c.closeAt!,'Europe/London')} LON</span></div><div><strong>{c.country}</strong><span>{c.closeAt!==c.firstCloseAt?'Último fuso · começa a fechar às '+time(c.firstCloseAt!)+' BRT':c.cities.length+(c.cities.length===1?' município eleitoral':' municípios eleitorais')}</span></div></div>)}{!upcoming.length&&<p className="empty">Todos os horários previstos já passaram.</p>}</div><div className="aside-foot"><strong>Já encerrados · {closed.length} países / territórios</strong><div className="waiting-tags">{closed.map(c=><span key={c.country}>{c.country}{c.complete?' · totalização concluída':c.buComplete?' · BU completo':c.received?' · BU parcial':' · aguardando boletim'}</span>)}</div></div><p className="aside-intro">Filas podem prolongar a votação. Países com vários fusos aparecem pelo último encerramento previsto. Municípios com votação dispensada não entram na lista.</p></aside></div>
 <footer><span>Fonte oficial: <a href={data?.indexUrl??'https://resultados.tse.jus.br/oficial/ele2026/6257/dados/zz/zz-e006257-ab.json'} target="_blank" rel="noreferrer">JSON da API do TSE ↗</a>{data?.generated?' · Arquivo gerado: '+data.generated:''}</span><p>Países agrupados pelas jurisdições eleitorais do exterior. Bélgica e Luxemburgo aparecem juntos quando reunidos no arquivo de Bruxelas. Boletins são somados por seção, sem duplicar seções agregadas. Quando a totalização começa, os votos da API de resultados substituem a soma dos boletins. “Mais votado” exige totalização concluída de todos os municípios do grupo no TSE.</p></footer></main></>;
}
