import React,{useEffect,useState} from 'react';
import geometry from './brazil-map.json';
import officeSeed from './office-results.json';
import historySeed from './history-2022.json';
import {StateResult,integer,published,candidates} from './national-source';
const ufs=[...geometry.features].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
const ne=new Set(['AL','BA','CE','MA','PB','PE','PI','RN','SE']);
const num=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR');
const percent=(v:number|null|undefined)=>v==null?'—':(100*v).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
const points=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+' p.p.';
const arrowScale=3;
const movement=(v:number|null)=>v===null?'Sem dados':Math.abs(v)<0.05?'Sem mudança relevante':`${points(Math.abs(v))} para a ${v>0?'esquerda':'direita'}`;
function ShiftArrow({delta}:{delta:number|null}){if(delta===null)return <text textAnchor="middle" y="12" fill="#748190">·</text>;if(Math.abs(delta)<0.05)return <circle cy="8" r="2" fill="#748190"/>;const length=Math.abs(delta)*arrowScale,direction=delta>0?-1:1,tip=direction*length/2,start=-tip,neck=tip-direction*Math.min(7,length*.4),head=Math.min(5,length*.3),shaft=Math.min(1.6,length*.12);return <path className="shift-arrow" fill={delta>0?'#226baa':'#b32f67'} d={`M ${start} ${8-shaft} L ${neck} ${8-shaft} L ${neck} ${8-head} L ${tip} 8 L ${neck} ${8+head} L ${neck} ${8+shaft} L ${start} ${8+shaft} Z`}/>;}
type History={lula:number;pl:number;source:string;error?:string};
const offices=[{id:'governador',name:'Governador',code:'3'},{id:'senado',name:'Senado',code:'5'},{id:'deputado-federal',name:'Deputados federais',code:'6'},{id:'deputado-estadual',name:'Deputados estaduais / distritais',code:'7'}] as const;
type Office=typeof offices[number];
type OfficeResult={data:any;source:string;error?:string;stale?:boolean};
const officeCache:Record<string,OfficeResult>=officeSeed;
function officeCandidates(d:any,code:string){const cargo=(d.carg??[]).find((c:any)=>c.cd===code);return (cargo?.agr??[]).flatMap((a:any)=>(a.par??[]).flatMap((p:any)=>(p.cand??[]).map((c:any)=>({number:c.n,name:c.nmu??c.nm,party:p.sg,votes:integer(c.vap),pct:typeof c.pvapn==='string'?Number(c.pvapn.replace(',','.'))/100:null})))).sort((a:any,b:any)=>(b.votes??0)-(a.votes??0));}
export default function StateOffices({results}:{results:Record<string,StateResult>}){
 const history:Record<string,History>=historySeed; const [selected,setSelected]=useState('SP');
 const [office,setOffice]=useState<Office>(offices[0]),[uf,setUf]=useState('SP'),[officeResult,setOfficeResult]=useState<OfficeResult|null>(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let cancel=false;let busy=false;const code=office.id==='deputado-estadual'&&uf==='DF'?'8':office.code;const source=`https://resultados.tse.jus.br/oficial/ele2026/6259/dados/${uf.toLowerCase()}/${uf.toLowerCase()}-c${code.padStart(4,'0')}-e006259-u.json`;const key=uf+code;
 const update=async()=>{if(busy)return;busy=true;setLoading(true);try{const r=await fetch(source,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(16000)});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.ele!=='6259'||d.t!=='1'||d.f!=='o'||d.tpabr!=='uf'||d.cdabr!==uf.toLowerCase()||d.dg!=='04/10/2026'||!['04/10/2026','05/10/2026'].includes(d.dt)||d.dv==='n'||(integer(d.s?.st)??0)===0||!Array.isArray(d.carg)||!d.carg.some((c:any)=>c.cd===code))throw Error('Sem resultado atual validado para este cargo');const value={data:d,source};officeCache[key]=value;if(!cancel)setOfficeResult(value);}catch(e){if(!cancel)setOfficeResult({...officeCache[key],data:officeCache[key]?.data??null,source,error:(e as Error).message,stale:!!officeCache[key]});}finally{busy=false;if(!cancel)setLoading(false);}};
 setOfficeResult(officeCache[key]??null);update();const timer=setInterval(update,30000);return()=>{cancel=true;clearInterval(timer);};},[office,uf]);
 const rows=ufs.map(f=>{const d=results[f.uf]?.data;const valid=published(d);const cs=valid?candidates(d):[];const lula=cs.find(c=>c.number==='13')?.votes??null,pl=cs.find(c=>c.number==='22')?.votes??null,h=history[f.uf];const margin=lula!==null&&pl!==null&&lula+pl>0?(lula-pl)/(lula+pl):null;const prior=h?(h.lula-h.pl)/(h.lula+h.pl):null;return {...f,margin,prior,delta:margin!==null&&prior!==null?(margin-prior)*100:null,processed:valid?integer(d.s?.st):null,total:valid?integer(d.s?.ts):null,stale:results[f.uf]?.stale};});
 const groups=(region:boolean)=>rows.filter(r=>ne.has(r.uf)===region).reduce((a,r)=>{const d=results[r.uf]?.data;if(!published(d))return a;const cs=candidates(d);a.lula+=cs.find(c=>c.number==='13')?.votes??0;a.pl+=cs.find(c=>c.number==='22')?.votes??0;a.states++;return a;},{lula:0,pl:0,states:0});const northeast=groups(true),others=groups(false);
 const active=rows.find(r=>r.uf===selected)!;
 const data=officeResult?.data,code=office.id==='deputado-estadual'&&uf==='DF'?'8':office.code,all=data?officeCandidates(data,code):[],filtered=all.filter((v:any)=>(v.name+' '+v.number+' '+v.party).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).slice(0,100),coverage=data&&integer(data.s?.ts)?(integer(data.s?.st)??0)/(integer(data.s.ts)??1):null;
 return <>
 <section className="national-section shift-section" id="comparacao-2022"><div className="section-title"><h2>Movimento à esquerda ou à direita desde 2022</h2><span>Presidente · primeiro turno de cada eleição</span></div><p>← Esquerda (azul): ganho de Lula. Direita (vermelho) →: ganho do candidato do PL. O comprimento é proporcional ao tamanho da mudança: uma seta de 10 pontos percentuais tem o dobro do comprimento de uma de 5. A comparação usa Lula versus Jair Bolsonaro em 2022 e Lula versus Flávio Bolsonaro em 2026. A seta mede a mudança do saldo entre esses dois candidatos, em pontos percentuais dos votos recebidos por ambos. Esquerda e direita são rótulos para esse deslocamento eleitoral entre Lula e PL, não uma classificação de todos os candidatos. A comparação permanece parcial enquanto a apuração de 2026 avança.</p>
 <div className="shift-legend"><span>← Esquerda · Lula</span><span>Direita · PL →</span><span>Escala: 10 p.p. <svg width="50" height="24" viewBox="-25 -4 50 24" role="img" aria-label="Seta de referência de 10 pontos percentuais"><ShiftArrow delta={-10}/></svg></span></div><div className="shift-layout"><div className="shift-map"><svg viewBox={geometry.viewBox} role="img" aria-label="Mapa: setas para esquerda ou direita com comprimento proporcional à mudança desde 2022"><g>{geometry.features.map(f=>{const r=rows.find(x=>x.uf===f.uf)!;return <path key={f.uf} d={f.path} fill={r.delta===null?'#e5e9ed':r.delta>=0?'#c8ddeb':'#f1ccda'} stroke="#fff" strokeWidth="1.5" onPointerEnter={()=>setSelected(f.uf)} onClick={()=>setSelected(f.uf)}><title>{f.name}: {points(r.delta)}; {percent(r.processed&&r.total?r.processed/r.total:null)} das seções de 2026</title></path>;})}</g><g className="shift-markers">{rows.map(r=><g key={r.uf} transform={`translate(${r.x},${r.y})`} onPointerEnter={()=>setSelected(r.uf)} onClick={()=>setSelected(r.uf)}><text textAnchor="middle" y="-6" className="shift-uf">{r.uf}</text><ShiftArrow delta={r.delta}/><title>{r.name}: {movement(r.delta)}</title></g>)}</g></svg></div><aside className="shift-detail"><label>UF <select value={selected} onChange={e=>setSelected(e.target.value)}>{ufs.map(f=><option key={f.uf} value={f.uf}>{f.name}</option>)}</select></label><h3>{active.name}</h3><p>2022 · saldo Lula − Jair Bolsonaro: <b>{points(active.prior===null?null:active.prior*100)}</b></p><p>2026 · saldo Lula − Flávio Bolsonaro: <b>{points(active.margin===null?null:active.margin*100)}</b></p><p>Movimento desde 2022: <strong>{movement(active.delta)}</strong></p><p className="freshness">Mudança do saldo Lula − PL: {points(active.delta)}.</p><p>Seções 2026: {num(active.processed)} de {num(active.total)} ({percent(active.processed!==null&&active.total?active.processed/active.total:null)}). {active.stale?'Leitura de 2026 antiga.':''}</p><p className="freshness">{history[selected]?<a href={history[selected].source} target="_blank" rel="noreferrer">Dados oficiais de 2022 ↗</a>:'Referência oficial de 2022 indisponível nesta consulta.'}</p></aside></div>
 <p className="map-read-warning">Referência de 2022: votação nominal oficial por município/zona, primeiro turno, agregada por UF e conferida com os totais nacionais. Resultados de 2026 ainda parciais e com horários diferentes; nenhuma mudança deve ser interpretada como resultado final.</p>
 <div className="ne-panel"><h3>Quanto o Nordeste pesa na diferença atual</h3><p>Nas {northeast.states} UFs nordestinas com dados: Lula {num(northeast.lula)} × Flávio {num(northeast.pl)}; saldo {num(northeast.lula-northeast.pl)}. Nas {others.states} demais UFs com dados: Lula {num(others.lula)} × Flávio {num(others.pl)}; saldo {num(others.lula-others.pl)}.</p><p>Diferença conjunta destas 27 UFs: {num(northeast.lula+others.lula-northeast.pl-others.pl)} votos. É uma soma dos resultados estaduais disponíveis, não uma projeção das urnas restantes. O total nacional pode ter horário diferente e inclui o exterior.</p></div></section>
 <section className="national-section offices-section" id="outros-cargos"><div className="section-title"><h2>Governador, Senado e deputados</h2><span>Primeiro turno · resultados estaduais do TSE</span></div><div className="office-tabs" role="tablist" aria-label="Escolha o cargo">{offices.map(o=><button key={o.id} role="tab" aria-selected={office.id===o.id} className={office.id===o.id?'active':''} onClick={()=>{setOffice(o);setSearch('');}}>{o.name}</button>)}</div><div className="national-tools"><label>UF<select value={uf} onChange={e=>setUf(e.target.value)}>{ufs.map(f=><option key={f.uf} value={f.uf}>{f.name} ({f.uf})</option>)}</select></label><label>Candidato, número ou partido<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar neste cargo"/></label></div>
 {loading&&<p className="freshness">Consultando TSE…</p>}{officeResult?.error&&<p className="map-read-warning">Consulta oficial: {officeResult.error}. {officeResult.stale?'Última leitura disponível abaixo.':'Sem dados atuais validados; votos indisponíveis.'}</p>}
 {data&&<><p><b>{percent(coverage)} das seções totalizadas</b> · {num(integer(data.s?.st))} de {num(integer(data.s?.ts))} · {data.and==='f'&&integer(data.s?.snt)===0?'concluído':'parcial'} · arquivo gerado em {data.dg} {data.hg} (horário literal do TSE).</p><div className="ranking-scroll"><table className="municipal-table office-table"><thead><tr><th>Candidato</th><th>Partido</th><th>Votos</th><th>% TSE</th></tr></thead><tbody>{filtered.map((c:any)=><tr key={c.number}><td>{c.name} <small>{c.number}</small></td><td>{c.party}</td><td>{num(c.votes)}</td><td>{percent(c.pct)}</td></tr>)}</tbody></table></div><p className="freshness">{filtered.length} de {all.length} candidatos exibidos; use a busca para encontrar outros. <a href={officeResult?.source} target="_blank" rel="noreferrer">Abrir JSON oficial ↗</a></p></>}
 <p className="aside-intro">Cada cargo tem sua própria apuração. A liderança em votos de deputado não determina, sozinha, as cadeiras obtidas pela regra proporcional. As percentagens e a situação são mostradas apenas quando o arquivo oficial atual foi validado; indisponibilidade não equivale a zero voto.</p></section></>;
}
